### ISSUE TITLE
build program on windows

### ISSUE THREAD

**Issue by justfrom** [meistdan/hippie#1]
Hi, @meistdan, nice paper and appreciated sharing the code. Need your help to build the project with CUDA **on windows**. 
I already set  CUDA_USE_CUDA on, but got the below error. Looks like it still needs HIP library. But after did some search,  HIP seems no support on windows. How did you get it working on windows? Thanks

```
hippie\src\hippie\Globals.h(18,10): fatal error C1083: Cannot open include file: 'hip/hip_runtime_api.h': No such file or directory
```

**Comment by charleswh** [comment]
@justfrom HIP can be installed on windows, follow steps may helpful.
1. Install Perl: [Strawberry Perl for Windows](https://strawberryperl.com/)
2. Refer to the install readme: hipamd/INSTALL.md, 
   download 4 required git reops:
   git clone https://github.com/ROCm-Developer-Tools/hipamd.git
   git clone https://github.com/ROCm-Developer-Tools/hip.git
   git clone https://github.com/ROCm-Developer-Tools/ROCclr.git
   git clone https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime.git
3. Open CMakeLists.txt in hipamd, and add **set(HIP_PLATFORM "nvidia")**  at line 204
4. cmake .. -DHIP_COMMON_DIR="d:\github\HIP" -DAMD_OPENCL_PATH=$OPENCL_DIR -DROCCLR_PATH="d:\github\ROCclr" -DCMAKE_INSTALL_PREFIX=C:/libs/hip
5. Set environment variable HIP_DIR=c:\libs\hip

**Comment by justfrom** [comment]
Thanks so much, @meistdan. Now I can set up the hip environment with cuda on windows and run your case successfully.
